// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package pipe

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}
	customPreCompare(delta, a, b)

	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Enrichment, b.ko.Spec.Enrichment) {
		delta.Add("Spec.Enrichment", a.ko.Spec.Enrichment, b.ko.Spec.Enrichment)
	} else if a.ko.Spec.Enrichment != nil && b.ko.Spec.Enrichment != nil {
		if *a.ko.Spec.Enrichment != *b.ko.Spec.Enrichment {
			delta.Add("Spec.Enrichment", a.ko.Spec.Enrichment, b.ko.Spec.Enrichment)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.LogConfiguration, b.ko.Spec.LogConfiguration) {
		delta.Add("Spec.LogConfiguration", a.ko.Spec.LogConfiguration, b.ko.Spec.LogConfiguration)
	} else if a.ko.Spec.LogConfiguration != nil && b.ko.Spec.LogConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination, b.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination) {
			delta.Add("Spec.LogConfiguration.CloudwatchLogsLogDestination", a.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination, b.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination)
		} else if a.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination != nil && b.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination.LogGroupARN, b.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination.LogGroupARN) {
				delta.Add("Spec.LogConfiguration.CloudwatchLogsLogDestination.LogGroupARN", a.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination.LogGroupARN, b.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination.LogGroupARN)
			} else if a.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination.LogGroupARN != nil && b.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination.LogGroupARN != nil {
				if *a.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination.LogGroupARN != *b.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination.LogGroupARN {
					delta.Add("Spec.LogConfiguration.CloudwatchLogsLogDestination.LogGroupARN", a.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination.LogGroupARN, b.ko.Spec.LogConfiguration.CloudwatchLogsLogDestination.LogGroupARN)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LogConfiguration.FirehoseLogDestination, b.ko.Spec.LogConfiguration.FirehoseLogDestination) {
			delta.Add("Spec.LogConfiguration.FirehoseLogDestination", a.ko.Spec.LogConfiguration.FirehoseLogDestination, b.ko.Spec.LogConfiguration.FirehoseLogDestination)
		} else if a.ko.Spec.LogConfiguration.FirehoseLogDestination != nil && b.ko.Spec.LogConfiguration.FirehoseLogDestination != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.LogConfiguration.FirehoseLogDestination.DeliveryStreamARN, b.ko.Spec.LogConfiguration.FirehoseLogDestination.DeliveryStreamARN) {
				delta.Add("Spec.LogConfiguration.FirehoseLogDestination.DeliveryStreamARN", a.ko.Spec.LogConfiguration.FirehoseLogDestination.DeliveryStreamARN, b.ko.Spec.LogConfiguration.FirehoseLogDestination.DeliveryStreamARN)
			} else if a.ko.Spec.LogConfiguration.FirehoseLogDestination.DeliveryStreamARN != nil && b.ko.Spec.LogConfiguration.FirehoseLogDestination.DeliveryStreamARN != nil {
				if *a.ko.Spec.LogConfiguration.FirehoseLogDestination.DeliveryStreamARN != *b.ko.Spec.LogConfiguration.FirehoseLogDestination.DeliveryStreamARN {
					delta.Add("Spec.LogConfiguration.FirehoseLogDestination.DeliveryStreamARN", a.ko.Spec.LogConfiguration.FirehoseLogDestination.DeliveryStreamARN, b.ko.Spec.LogConfiguration.FirehoseLogDestination.DeliveryStreamARN)
				}
			}
		}
		if len(a.ko.Spec.LogConfiguration.IncludeExecutionData) != len(b.ko.Spec.LogConfiguration.IncludeExecutionData) {
			delta.Add("Spec.LogConfiguration.IncludeExecutionData", a.ko.Spec.LogConfiguration.IncludeExecutionData, b.ko.Spec.LogConfiguration.IncludeExecutionData)
		} else if len(a.ko.Spec.LogConfiguration.IncludeExecutionData) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.LogConfiguration.IncludeExecutionData, b.ko.Spec.LogConfiguration.IncludeExecutionData) {
				delta.Add("Spec.LogConfiguration.IncludeExecutionData", a.ko.Spec.LogConfiguration.IncludeExecutionData, b.ko.Spec.LogConfiguration.IncludeExecutionData)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LogConfiguration.Level, b.ko.Spec.LogConfiguration.Level) {
			delta.Add("Spec.LogConfiguration.Level", a.ko.Spec.LogConfiguration.Level, b.ko.Spec.LogConfiguration.Level)
		} else if a.ko.Spec.LogConfiguration.Level != nil && b.ko.Spec.LogConfiguration.Level != nil {
			if *a.ko.Spec.LogConfiguration.Level != *b.ko.Spec.LogConfiguration.Level {
				delta.Add("Spec.LogConfiguration.Level", a.ko.Spec.LogConfiguration.Level, b.ko.Spec.LogConfiguration.Level)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LogConfiguration.S3LogDestination, b.ko.Spec.LogConfiguration.S3LogDestination) {
			delta.Add("Spec.LogConfiguration.S3LogDestination", a.ko.Spec.LogConfiguration.S3LogDestination, b.ko.Spec.LogConfiguration.S3LogDestination)
		} else if a.ko.Spec.LogConfiguration.S3LogDestination != nil && b.ko.Spec.LogConfiguration.S3LogDestination != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.LogConfiguration.S3LogDestination.BucketName, b.ko.Spec.LogConfiguration.S3LogDestination.BucketName) {
				delta.Add("Spec.LogConfiguration.S3LogDestination.BucketName", a.ko.Spec.LogConfiguration.S3LogDestination.BucketName, b.ko.Spec.LogConfiguration.S3LogDestination.BucketName)
			} else if a.ko.Spec.LogConfiguration.S3LogDestination.BucketName != nil && b.ko.Spec.LogConfiguration.S3LogDestination.BucketName != nil {
				if *a.ko.Spec.LogConfiguration.S3LogDestination.BucketName != *b.ko.Spec.LogConfiguration.S3LogDestination.BucketName {
					delta.Add("Spec.LogConfiguration.S3LogDestination.BucketName", a.ko.Spec.LogConfiguration.S3LogDestination.BucketName, b.ko.Spec.LogConfiguration.S3LogDestination.BucketName)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.LogConfiguration.S3LogDestination.BucketOwner, b.ko.Spec.LogConfiguration.S3LogDestination.BucketOwner) {
				delta.Add("Spec.LogConfiguration.S3LogDestination.BucketOwner", a.ko.Spec.LogConfiguration.S3LogDestination.BucketOwner, b.ko.Spec.LogConfiguration.S3LogDestination.BucketOwner)
			} else if a.ko.Spec.LogConfiguration.S3LogDestination.BucketOwner != nil && b.ko.Spec.LogConfiguration.S3LogDestination.BucketOwner != nil {
				if *a.ko.Spec.LogConfiguration.S3LogDestination.BucketOwner != *b.ko.Spec.LogConfiguration.S3LogDestination.BucketOwner {
					delta.Add("Spec.LogConfiguration.S3LogDestination.BucketOwner", a.ko.Spec.LogConfiguration.S3LogDestination.BucketOwner, b.ko.Spec.LogConfiguration.S3LogDestination.BucketOwner)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.LogConfiguration.S3LogDestination.Prefix, b.ko.Spec.LogConfiguration.S3LogDestination.Prefix) {
				delta.Add("Spec.LogConfiguration.S3LogDestination.Prefix", a.ko.Spec.LogConfiguration.S3LogDestination.Prefix, b.ko.Spec.LogConfiguration.S3LogDestination.Prefix)
			} else if a.ko.Spec.LogConfiguration.S3LogDestination.Prefix != nil && b.ko.Spec.LogConfiguration.S3LogDestination.Prefix != nil {
				if *a.ko.Spec.LogConfiguration.S3LogDestination.Prefix != *b.ko.Spec.LogConfiguration.S3LogDestination.Prefix {
					delta.Add("Spec.LogConfiguration.S3LogDestination.Prefix", a.ko.Spec.LogConfiguration.S3LogDestination.Prefix, b.ko.Spec.LogConfiguration.S3LogDestination.Prefix)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RoleARN, b.ko.Spec.RoleARN) {
		delta.Add("Spec.RoleARN", a.ko.Spec.RoleARN, b.ko.Spec.RoleARN)
	} else if a.ko.Spec.RoleARN != nil && b.ko.Spec.RoleARN != nil {
		if *a.ko.Spec.RoleARN != *b.ko.Spec.RoleARN {
			delta.Add("Spec.RoleARN", a.ko.Spec.RoleARN, b.ko.Spec.RoleARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Source, b.ko.Spec.Source) {
		delta.Add("Spec.Source", a.ko.Spec.Source, b.ko.Spec.Source)
	} else if a.ko.Spec.Source != nil && b.ko.Spec.Source != nil {
		if *a.ko.Spec.Source != *b.ko.Spec.Source {
			delta.Add("Spec.Source", a.ko.Spec.Source, b.ko.Spec.Source)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Target, b.ko.Spec.Target) {
		delta.Add("Spec.Target", a.ko.Spec.Target, b.ko.Spec.Target)
	} else if a.ko.Spec.Target != nil && b.ko.Spec.Target != nil {
		if *a.ko.Spec.Target != *b.ko.Spec.Target {
			delta.Add("Spec.Target", a.ko.Spec.Target, b.ko.Spec.Target)
		}
	}

	return delta
}
