# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS EventBridge Pipes controller is a service controller for managing Pipes resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon EventBridge Pipes
description: |-
  Manage Amazon EventBridge Pipes resources in AWS from within your Kubernetes cluster.


  **About Amazon EventBridge Pipes**


  Amazon EventBridge Pipes connects sources to targets. Pipes are intended for point-to-point integrations between supported [sources](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes-event-source.html)
  and [targets](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes-event-target.html), with support for advanced transformations and [enrichment](https://docs.aws.amazon.com/eventbridge/latest/userguide/pipes-enrichment.html). 
  It reduces the need for specialized knowledge and integration code when developing event-driven architectures, fostering consistency across your company’s applications. To set up a pipe, you choose the source, 
  add optional filtering, define optional enrichment, and choose the target for the event data.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples:
- kind: Pipe
  spec: '{}'
maintainers:
- name: "pipes maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon EventBridge Pipes Developer Resources
  url: https://aws.amazon.com/eventbridge/pipes/
